<?php

namespace ContainerH9JxfxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ChkevrnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Chkevrn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Chkevrn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contest' => ['privates', '.errored..service_locator.Chkevrn.App\\Entity\\Contest', NULL, 'Cannot autowire service ".service_locator.Chkevrn": it references class "App\\Entity\\Contest" but no such service exists.'],
        ], [
            'contest' => 'App\\Entity\\Contest',
        ]);
    }
}
