<?php

namespace ContainerH9JxfxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JKMmXsiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jKMmXsi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jKMmXsi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'player' => ['privates', '.errored..service_locator.jKMmXsi.App\\Entity\\Player', NULL, 'Cannot autowire service ".service_locator.jKMmXsi": it references class "App\\Entity\\Player" but no such service exists.'],
        ], [
            'player' => 'App\\Entity\\Player',
        ]);
    }
}
