<?php

namespace ContainerH9JxfxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IL0qtQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IL0qtQL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IL0qtQL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contest' => ['privates', '.errored..service_locator.IL0qtQL.App\\Entity\\Contest', NULL, 'Cannot autowire service ".service_locator.IL0qtQL": it references class "App\\Entity\\Contest" but no such service exists.'],
            'contestRepository' => ['privates', 'App\\Repository\\ContestRepository', 'getContestRepositoryService', true],
        ], [
            'contest' => 'App\\Entity\\Contest',
            'contestRepository' => 'App\\Repository\\ContestRepository',
        ]);
    }
}
