<?php

namespace ContainerH9JxfxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommencerPartieTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CommencerPartieType' shared autowired service.
     *
     * @return \App\Form\CommencerPartieType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CommencerPartieType.php';

        return $container->privates['App\\Form\\CommencerPartieType'] = new \App\Form\CommencerPartieType();
    }
}
