<?php

namespace ContainerE2jneRu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A9G3iZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A9G3i_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A9G3i_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contestRepository' => ['privates', 'App\\Repository\\ContestRepository', 'getContestRepositoryService', true],
        ], [
            'contestRepository' => 'App\\Repository\\ContestRepository',
        ]);
    }
}
