<?php

namespace ContainerE2jneRu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IL0qtQL.App\Entity\Contest' shared service.
     *
     * @return \App\Entity\Contest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IL0qtQL": it references class "App\\Entity\\Contest" but no such service exists.');
    }
}
