<?php

namespace ContainerE2jneRu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayer2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jKMmXsi.App\Entity\Player' shared service.
     *
     * @return \App\Entity\Player
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jKMmXsi": it references class "App\\Entity\\Player" but no such service exists.');
    }
}
