<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9JxfxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9JxfxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9JxfxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9JxfxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH9JxfxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'H9JxfxC',
    'container.build_id' => 'a7514042',
    'container.build_time' => 1653753379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9JxfxC');
